#!/usr/bin/env bash

#TODO This script is duplicated between opsbox-action and opsbox-docker, please ref https://jira.it.wirelesscar.com/browse/CYC-492

set -euox pipefail

SOURCE="$1"

function check_deps() {
  test -f $(which az) || error_exit "Azure cli command not detected in path, please install it"
  VALID=$(az account get-access-token --query "expiresOn" --output tsv)
  VALID_SEC=$(date --date "$VALID" +'%s')
  NOW_SEC=$(date +'%s')

  [[ "$NOW_SEC" -lt "$VALID_SEC" ]] || error_exit "Please run 'az login' to setup account"
}

function parse_input() {
  INPUT_ARRAY=(${SOURCE//\// })
  DOCKER_NAME=${INPUT_ARRAY[-1]}

  INPUT_ARRAY=(${DOCKER_NAME//:/ })
  DOCKER_TAG=${INPUT_ARRAY[-1]}
  DOCKER_NAME=${INPUT_ARRAY[-2]}

  [[ -n "${DOCKER_NAME}" ]] || error_exit "Unable to parse input docker name missing."
  [[ -n "${DOCKER_TAG}" ]] || error_exit "Unable to parse input docker tag missing."
}

function import_docker() {
    az acr import -n wcorn --source "${SOURCE}" -t "wcorn.azurecr.io/external/${DOCKER_NAME}:${DOCKER_TAG}" --force
}

check_deps && \
parse_input && \
import_docker
