#!/usr/bin/env bash

#TODO This script is duplicated between opsbox-action and opsbox-docker, please ref https://jira.it.wirelesscar.com/browse/CYC-492

set -euox pipefail

MAJOR=$(<version/major tr -d '\r')
MINOR=$(<version/minor tr -d '\r')
PATCH=$(<version/patch tr -d '\r')

METADATA=$(date +'%Y%m%d_%H%M%SZ')
RELEASE="${MAJOR}.${MINOR}.${PATCH}"
BUILD="${MAJOR}.${MINOR}.${PATCH}-${METADATA}"

\cp -TR version/ out/source/version/

pushd out/source
git add version/* ||:
git commit -m $RELEASE ||:
git tag -a $BUILD -m $BUILD ||:
popd

pushd out/target
git add . ||:
git commit -m $RELEASE ||:
  git tag -a $BUILD -m $BUILD ||:
  git push origin ||:
  git push origin $BUILD ||:

popd
pushd out/source
git push origin ||:
git push origin $BUILD ||:
  