name: Lint files

on: [pull_request]

jobs:
  dockerlint:
    name: Dockerfile lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: bltavares/actions/hadolint@master
